# Generated by Django 2.0.4 on 2018-04-21 10:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub1', models.CharField(blank=True, max_length=100)),
                ('subhours1', models.FloatField(blank=True)),
                ('sub2', models.CharField(blank=True, max_length=100)),
                ('subhours2', models.FloatField(blank=True)),
                ('sub3', models.CharField(blank=True, max_length=100)),
                ('subhours3', models.FloatField(blank=True)),
                ('sub4', models.CharField(blank=True, max_length=100)),
                ('subhours4', models.FloatField(blank=True)),
                ('sub5', models.CharField(blank=True, max_length=100)),
                ('subhours5', models.FloatField(blank=True)),
                ('sub6', models.CharField(blank=True, max_length=100)),
                ('subhours6', models.FloatField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(blank=True, max_length=200)),
                ('sem', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(8)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
