# Generated by Django 2.0.4 on 2018-04-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
